FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json .
RUN npm ci
COPY . .

# Accept build arguments for public environment variables
ARG PUBLIC_FIREBASE_API_KEY
ARG PUBLIC_FIREBASE_AUTH_DOMAIN
ARG PUBLIC_FIREBASE_PROJECT_ID
ARG PUBLIC_FIREBASE_STORAGE_BUCKET
ARG PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG PUBLIC_FIREBASE_APP_ID
ARG PUBLIC_BOOKSAPI_KEY
ARG PUBLIC_BOOKSAPI_LIST

# Accept build arguments for private environment variables
ARG FIREBASE_ADMIN_PRIVATE_KEY
ARG FIREBASE_ADMIN_CLIENT_EMAIL
ARG MONGO_URL
ARG DB_NAME
ARG BOOKINFOS_COLLECTION_NAME
ARG BOOKSHELVES_COLLECTION_NAME

# Set environment variables for build
ENV PUBLIC_FIREBASE_API_KEY=$PUBLIC_FIREBASE_API_KEY
ENV PUBLIC_FIREBASE_AUTH_DOMAIN=$PUBLIC_FIREBASE_AUTH_DOMAIN
ENV PUBLIC_FIREBASE_PROJECT_ID=$PUBLIC_FIREBASE_PROJECT_ID
ENV PUBLIC_FIREBASE_STORAGE_BUCKET=$PUBLIC_FIREBASE_STORAGE_BUCKET
ENV PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV PUBLIC_FIREBASE_APP_ID=$PUBLIC_FIREBASE_APP_ID
ENV PUBLIC_BOOKSAPI_KEY=$PUBLIC_BOOKSAPI_KEY
ENV PUBLIC_BOOKSAPI_LIST=$PUBLIC_BOOKSAPI_LIST
ENV FIREBASE_ADMIN_PRIVATE_KEY=$FIREBASE_ADMIN_PRIVATE_KEY
ENV FIREBASE_ADMIN_CLIENT_EMAIL=$FIREBASE_ADMIN_CLIENT_EMAIL
ENV MONGO_URL=$MONGO_URL
ENV DB_NAME=$DB_NAME
ENV BOOKINFOS_COLLECTION_NAME=$BOOKINFOS_COLLECTION_NAME
ENV BOOKSHELVES_COLLECTION_NAME=$BOOKSHELVES_COLLECTION_NAME

RUN npm run build
RUN npm prune --production

FROM node:22-alpine AS runner
WORKDIR /app
COPY --from=builder /app/build build/
COPY --from=builder /app/node_modules node_modules/
COPY package.json .
EXPOSE 3000
ENV NODE_ENV=production
CMD ["node", "build"]