name: Deployment Workflow

on:
  push: 
    branches: [ $default-branch ]

jobs:
  test: 
    uses: ./.github/workflows/TestWorkflow.yml
  
  deploy:
    name: Deploy
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
