# プルリクエストを作成したタイミングなどでテストコードを実行する。
# CDに関連する処理はVercelが自動でやってくれるので対応無し

name: Integration

on:
  pull_request: 
    branches: 
      - main

env: 
  # UIテスト用の変数
  TEST_LOGIN_EMAIL: ${{secrets.TEST_LOGIN_EMAIL}}
  TEST_LOGIN_PASSWORD: ${{secrets.TEST_LOGIN_PASSWORD}}
  
  MONGO_URL: ${{secrets.MONGO_URL}}
  DB_NAME: ${{secrets.TEST_DB_NAME}}
  BOOKINFOS_COLLECTION_NAME: ${{secrets.BOOKINFOS_COLLECTION_NAME}}
  PUBLIC_BOOKSAPI_LIST: ${{vars.PUBLIC_BOOKSAPI_LIST}}
  PUBLIC_FIREBASE_API_KEY: ${{vars.PUBLIC_FIREBASE_API_KEY}}
  PUBLIC_FIREBASE_AUTH_DOMAIN: ${{vars.PUBLIC_FIREBASE_AUTH_DOMAIN}}
  PUBLIC_FIREBASE_PROJECT_ID: ${{vars.PUBLIC_FIREBASE_PROJECT_ID}}
  PUBLIC_FIREBASE_STORAGE_BUCKET: ${{vars.PUBLIC_FIREBASE_STORAGE_BUCKET}}
  PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{vars.PUBLIC_FIREBASE_MESSAGING_SENDER_ID}}
  PUBLIC_FIREBASE_APP_ID: ${{vars.PUBLIC_FIREBASE_APP_ID}}
  FIREBASE_ADMIN_PRIVATE_KEY: ${{secrets.FIREBASE_ADMIN_PRIVATE_KEY}}
  FIREBASE_ADMIN_CLIENT_EMAIL: ${{secrets.FIREBASE_ADMIN_CLIENT_EMAIL}}

jobs: 
  test:
    name: Test and build triggered by pull request
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: UnitTest
        run: npm run test:unit
        
      - name: UITest
        run: npm run test:ui