name: Test Workflow

on:
  pull_request: 
    branches: 
      - main

jobs: 
  test:
    name: Test workflow triggered by ${{ github.event_name }}
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build

      - name: Test
        run: npm run test:unit