name: Test Workflow

on:
  pull_request: 
    branches: 
      - main

env: 
  MONGO_URL: ${{secrets.TEST_MONGO_URL}}
  DB_NAME: ${{secrets.TEST_DB_NAME}}
  BOOKINFOS_COLLECTION_NAME: ${{secrets.BOOKINFOS_COLLECTION_NAME}}
  PUBLIC_BOOKSAPI_LIST: ${{vars.PUBLIC_BOOKSAPI_LIST}}

jobs: 
  test:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build

      - name: Test
        run: npm run test:unit